// scripts/parse_vk_to_rust.js
const fs = require("fs");
const path = require("path");

const VK_PATH = process.argv[2] || "./verification_key.json";

function toHex(n) {
  let hex = BigInt(n).toString(16);
  if (hex.length % 2 !== 0) {
    hex = "0" + hex;
  }
  return hex.padStart(64, "0"); // Pad to 32 bytes
}

function toRustBytes(n) {
  const hex = BigInt(n).toString(16).padStart(64, "0");
  const pairs = hex.match(/.{1,2}/g);
  return pairs.map((x) => "0x" + x).join(", ");
}

// G1 is just x, y
function parseG1(g1) {
  return `${toRustBytes(g1[0])}, ${toRustBytes(g1[1])}`;
}

// G2 is [[x0, x1], [y0, y1]]
// RUST STRUCT EXPECTS: 
// X = c1 (imaginary), c0 (real)
// Y = c1 (imaginary), c0 (real)
function parseG2(g2) {
  return `${toRustBytes(g2[0][1])}, ${toRustBytes(g2[0][0])}, ${toRustBytes(g2[1][1])}, ${toRustBytes(g2[1][0])}`;
}

try {
  const vk = JSON.parse(fs.readFileSync(VK_PATH, "utf8"));

  const alpha = parseG1(vk.vk_alpha_1);
  const beta = parseG2(vk.vk_beta_2);
  const gamma = parseG2(vk.vk_gamma_2);
  const delta = parseG2(vk.vk_delta_2);

  // IC (Input Commitments) - Array of G1 points
  const ic = vk.IC.map((p) => {
    return `        [
            ${parseG1(p)}
        ]`;
  }).join(",\n");

  const rustCode = `
// GENERATED BY parse_vk_to_rust.js
// PASTE THIS INTO YOUR lib.rs

pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.IC.length - 1},
    vk_alpha_g1: [
        ${alpha}
    ],
    vk_beta_g2: [
        ${beta}
    ],
    vk_gamme_g2: [
        ${gamma}
    ],
    vk_delta_g2: [
        ${delta}
    ],
    vk_ic: &[
${ic}
    ]
};
`;

  console.log(rustCode);
} catch (e) {
  console.error("Error parsing VK:", e);
  console.log("Usage: node parse_vk_to_rust.js <path_to_verification_key.json>");
}

