[package]
name = "pdx-dark-protocol"
version = "0.1.0"
description = "Dark Null canonical privacy settlement root"
edition = "2021"
license = "MIT"
authors = ["Parad0x Labs"]

[lib]
crate-type = ["cdylib", "lib"]
name = "pdx_dark_protocol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("anchor-debug", "custom-heap", "custom-panic", "no-idl", "no-log-ix-name"))',
] }

[dependencies]
anchor-lang = "1.0.3"
anchor-spl = "0.30.1"
bytemuck = { version = "1.16.0", features = ["derive", "min_const_generics"] }
base64 = "0.21.7"
spl-token = "4.0.3"
groth16-solana = "0.2.0"
ark-serialize = { version = "0.4.0", default-features = false, features = ["derive"] }
ark-bn254 = { version = "0.4.0", default-features = false, features = ["curve"] }
ark-ff = { version = "0.4.0", default-features = false }
ark-groth16 = { version = "0.4.0", default-features = false }
