// Generate program/src/vk.rs from snarkjs verification keys (sandbox).
// Usage: node gen_vk_rs.mjs <keysdir> <out vk.rs>
import fs from "node:fs";
const [dir, outPath] = process.argv.slice(2);
const R = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const W28 = 19103219067921713944291392827692070036145651957329286315305642004821462161904n;
const be = (x) => BigInt(x).toString(16).padStart(64, "0");
const bytes = (h) => h.match(/../g).map((b) => "0x" + b).join(", ");
const g1 = (p) => `[${bytes(be(p[0]) + be(p[1]))}]`;
const g2 = (p) => `[${bytes(be(p[0][1]) + be(p[0][0]) + be(p[1][1]) + be(p[1][0]))}]`; // x.c1 x.c0 y.c1 y.c0
const fr = (x) => `[${bytes(be(x))}]`;
const modpow = (b, e) => { let r = 1n; b %= R; while (e > 0n) { if (e & 1n) r = (r * b) % R; b = (b * b) % R; e >>= 1n; } return r; };
const omega = (power) => modpow(W28, 1n << BigInt(28 - power));
const load = (f) => JSON.parse(fs.readFileSync(`${dir}/${f}`, "utf8"));

let out = "//! Generated by spikes/p0/scripts/gen_vk_rs.mjs from snarkjs verification keys. dev-setup keys (Groth16).\n";
out += "use crate::fflonk::FflonkVk;\nuse crate::plonk::PlonkVk;\nuse groth16_solana::groth16::Groth16Verifyingkey;\n\n";
for (const [name, file] of [["SKELETON", "transact_v2_skeleton_g16_vk.json"], ["PI_HASH", "pi_hash_g16_vk.json"], ["FULLSIZE", "transact_v2_fullsize_g16_vk.json"]]) {
  const v = load(file);
  out += `pub const G16_${name}_IC: [[u8; 64]; ${v.IC.length}] = [${v.IC.map(g1).join(", ")}];\n`;
  out += `pub const G16_${name}: Groth16Verifyingkey = Groth16Verifyingkey { nr_pubinputs: ${v.nPublic}, vk_alpha_g1: ${g1(v.vk_alpha_1)}, vk_beta_g2: ${g2(v.vk_beta_2)}, vk_gamme_g2: ${g2(v.vk_gamma_2)}, vk_delta_g2: ${g2(v.vk_delta_2)}, vk_ic: &G16_${name}_IC };\n\n`;
}
for (const [name, file] of [["PI_HASH", "pi_hash_plonk_vk.json"], ["SKELETON", "transact_v2_skeleton_plonk_vk.json"]]) {
  const v = load(file);
  if (v.nPublic !== 1) throw new Error("nPublic must be 1");
  const comm = ["Qm", "Ql", "Qr", "Qo", "Qc", "S1", "S2", "S3"].map((k) => be(v[k][0]) + be(v[k][1])).join("");
  out += `pub const PLONK_${name}: PlonkVk = PlonkVk { power: ${v.power}, n: ${2 ** v.power}, k1: ${fr(v.k1)}, k2: ${fr(v.k2)}, omega: ${fr(omega(v.power))}, commitments: [${bytes(comm)}], x2: ${g2(v.X_2)} };\n\n`;
}
{
  const v = load("pi_hash_fflonk_vk.json");
  if (BigInt(v.w) !== omega(v.power)) throw new Error("fflonk w mismatch with computed omega");
  out += `pub const FFLONK_PI_HASH: FflonkVk = FflonkVk { power: ${v.power}, n: ${2 ** v.power}, k1: ${fr(v.k1)}, k2: ${fr(v.k2)}, w: ${fr(v.w)}, w3: ${fr(v.w3)}, w4: ${fr(v.w4)}, w8: ${fr(v.w8)}, wr: ${fr(v.wr)}, x2: ${g2(v.X_2)}, c0: ${g1(v.C0)} };\n`;
}
fs.writeFileSync(outPath, out);
console.log("wrote", outPath, out.length, "bytes");
