//! Deposit-to-withdrawal linkage reproduction for the current construction.
//!
//! What runs for real:
//! - the program entrypoint (`pdx_dark_protocol::entry`): Anchor dispatch, account
//!   constraints, `deposit_wsol_and_whisper`, `update_root`,
//!   `prepare_phantom_withdraw_v2`;
//! - the on-chain Groth16 verifier with the embedded `VERIFYING_KEY`, checking a
//!   real proof generated from `circuits/null_proof_js/null_proof.wasm` and
//!   `circuits/null_proof_final.zkey` (fixture: tests/fixtures/privacy-linkage.json,
//!   regenerated by scripts/generate-privacy-linkage-fixture.mjs);
//! - SPL Token transfers, executed by `spl_token::processor::Processor` through a
//!   native cross-program-invocation shim.
//!
//! Set up directly by the harness with the program's own account layouts:
//! the vault and root-authority accounts (what `initialize` writes) and nullifier
//! page 0 (what `init_nullifier_page` allocates). Those two instructions only
//! allocate accounts through the system program.
//!
//! The observer at the bottom receives only what a chain observer receives:
//! instruction data, account keys with signer/writable flags, program logs and
//! public account state. It never sees note openings, client memory or the fixture's
//! `test_only_note_openings`. The test asserts the CURRENT behaviour: the withdrawal
//! is linked to exactly one deposit by commitment equality. If the protocol changes
//! so that this no longer holds, this test must be updated together with
//! docs/PRIVACY_PROPERTIES.md.

use std::collections::HashMap;
use std::sync::Mutex;

use anchor_lang::prelude::*;
use anchor_lang::solana_program::{
    entrypoint::ProgramResult, instruction::Instruction, program_error::ProgramError,
    program_option::COption, program_pack::Pack, program_stubs,
};
use anchor_lang::{AccountSerialize, AnchorDeserialize, Discriminator, InstructionData, ToAccountMetas};
use pdx_dark_protocol::{accounts as ix_accounts, instruction as ix_args, NullifierPage, RootAuthorityConfig, Vault, ID};
use spl_token::state::{Account as TokenAccountState, AccountState, Mint as MintState};

const FIXTURE: &str = include_str!("fixtures/privacy-linkage.json");
// Anchor `ErrorCode::AccountNotSigner` and program error codes (6000 + variant index).
const ANCHOR_ACCOUNT_NOT_SIGNER: u32 = 3010;
const DOUBLE_SPEND: u32 = 6000;
const INVALID_PROOF: u32 = 6004;

// ---------------------------------------------------------------------------
// Fixture access (flat scanner; the fixture is generated, keys are stable)
// ---------------------------------------------------------------------------

fn find_from(src: &str, from: usize, needle: &str) -> usize {
    from + src[from..].find(needle).unwrap_or_else(|| panic!("fixture key missing: {needle}"))
}

fn string_after(src: &str, from: usize, key: &str) -> (String, usize) {
    let needle = format!("\"{key}\": \"");
    let start = find_from(src, from, &needle) + needle.len();
    let end = start + src[start..].find('"').expect("unterminated string");
    (src[start..end].to_string(), end)
}

fn hex_bytes<const N: usize>(hex: &str) -> [u8; N] {
    assert_eq!(hex.len(), N * 2, "unexpected hex length");
    let mut out = [0u8; N];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("hex");
    }
    out
}

struct Fixture {
    mint: Pubkey,
    root: [u8; 32],
    deposit_amount: u64,
    commitments: [[u8; 32]; 2],
    receiver: Pubkey,
    receiver_token: Pubkey,
    withdraw_amount: u64,
    nullifier: [u8; 32],
    proof_a: [u8; 64],
    proof_b: [u8; 128],
    proof_c: [u8; 64],
    public_inputs: [[u8; 32]; 8],
}

fn load_fixture() -> Fixture {
    let src = FIXTURE;
    let (mint, _) = string_after(src, 0, "mint_hex");
    let (root, _) = string_after(src, 0, "root_hex");
    let deposits = find_from(src, 0, "\"deposits\": [");
    let (deposit_amount, pos) = string_after(src, deposits, "amount");
    let (commitment_a, pos) = string_after(src, pos, "commitment_hex");
    let (commitment_b, _) = string_after(src, pos, "commitment_hex");
    let w = find_from(src, 0, "\"withdrawal\": {");
    let (receiver, _) = string_after(src, w, "receiver_hex");
    let (receiver_token, _) = string_after(src, w, "receiver_token_hex");
    let (withdraw_amount, _) = string_after(src, w, "amount");
    let (nullifier, _) = string_after(src, w, "nullifier_hex");
    let (proof_a, _) = string_after(src, w, "proof_a_hex");
    let (proof_b, _) = string_after(src, w, "proof_b_hex");
    let (proof_c, _) = string_after(src, w, "proof_c_hex");
    let mut public_inputs = [[0u8; 32]; 8];
    let list = "\"public_inputs_hex\": [";
    let mut pos = find_from(src, w, list) + list.len();
    for input in public_inputs.iter_mut() {
        let start = find_from(src, pos, "\"") + 1;
        let end = start + src[start..].find('"').unwrap();
        *input = hex_bytes::<32>(&src[start..end]);
        pos = end + 1;
    }
    Fixture {
        mint: Pubkey::new_from_array(hex_bytes(&mint)),
        root: hex_bytes(&root),
        deposit_amount: deposit_amount.parse().unwrap(),
        commitments: [hex_bytes(&commitment_a), hex_bytes(&commitment_b)],
        receiver: Pubkey::new_from_array(hex_bytes(&receiver)),
        receiver_token: Pubkey::new_from_array(hex_bytes(&receiver_token)),
        withdraw_amount: withdraw_amount.parse().unwrap(),
        nullifier: hex_bytes(&nullifier),
        proof_a: hex_bytes(&proof_a),
        proof_b: hex_bytes(&proof_b),
        proof_c: hex_bytes(&proof_c),
        public_inputs,
    }
}

// ---------------------------------------------------------------------------
// Minimal native execution harness
// ---------------------------------------------------------------------------

static LOGS: Mutex<Vec<String>> = Mutex::new(Vec::new());

struct NativeStubs;

impl program_stubs::SyscallStubs for NativeStubs {
    fn sol_log(&self, message: &str) {
        LOGS.lock().unwrap().push(message.to_string());
    }

    fn sol_log_data(&self, fields: &[&[u8]]) {
        LOGS.lock().unwrap().push(format!("Program data: {} fields", fields.len()));
    }

    fn sol_invoke_signed(
        &self,
        instruction: &Instruction,
        account_infos: &[AccountInfo],
        signers_seeds: &[&[&[u8]]],
    ) -> ProgramResult {
        // The only CPI target in the exercised paths is SPL Token.
        if instruction.program_id != spl_token::id() {
            return Err(ProgramError::IncorrectProgramId);
        }
        let pda_signers: Vec<Pubkey> = signers_seeds
            .iter()
            .map(|seeds| Pubkey::create_program_address(seeds, &ID).expect("valid signer seeds"))
            .collect();
        let mut infos = Vec::with_capacity(instruction.accounts.len());
        for meta in &instruction.accounts {
            let source = account_infos
                .iter()
                .find(|info| info.key == &meta.pubkey)
                .ok_or(ProgramError::NotEnoughAccountKeys)?;
            let mut info = source.clone();
            if meta.is_signer {
                if !(source.is_signer || pda_signers.contains(&meta.pubkey)) {
                    return Err(ProgramError::MissingRequiredSignature);
                }
                info.is_signer = true;
            }
            if meta.is_writable && !source.is_writable {
                return Err(ProgramError::InvalidArgument);
            }
            infos.push(info);
        }
        LOGS.lock().unwrap().push(format!("Program {} invoke", instruction.program_id));
        spl_token::processor::Processor::process(&instruction.program_id, &infos, &instruction.data)
    }
}

#[derive(Clone)]
struct LedgerAccount {
    lamports: u64,
    data: Vec<u8>,
    owner: Pubkey,
    executable: bool,
}

/// What a chain observer can read about one transaction.
#[derive(Clone, Debug)]
struct PublicTx {
    accounts: Vec<(Pubkey, bool, bool)>, // (key, is_signer, is_writable)
    data: Vec<u8>,
    logs: Vec<String>,
    success: bool,
}

#[derive(Default)]
struct Ledger {
    accounts: HashMap<Pubkey, LedgerAccount>,
    history: Vec<PublicTx>,
}

impl Ledger {
    fn put(&mut self, key: Pubkey, owner: Pubkey, data: Vec<u8>, executable: bool) {
        self.accounts.insert(key, LedgerAccount { lamports: 1_000_000_000, data, owner, executable });
    }

    /// Executes one instruction against the program entrypoint. State is committed
    /// only on success, matching transaction atomicity.
    fn process(&mut self, ix: &Instruction, record: bool) -> ProgramResult {
        assert_eq!(ix.program_id, ID);
        LOGS.lock().unwrap().clear();
        let mut infos: Vec<AccountInfo<'static>> = Vec::new();
        for meta in &ix.accounts {
            let acct = self.accounts.get(&meta.pubkey).cloned().unwrap_or_else(|| panic!("missing account {}", meta.pubkey));
            let key: &'static Pubkey = Box::leak(Box::new(meta.pubkey));
            let owner: &'static Pubkey = Box::leak(Box::new(acct.owner));
            let lamports: &'static mut u64 = Box::leak(Box::new(acct.lamports));
            let data: &'static mut [u8] = Box::leak(acct.data.into_boxed_slice());
            infos.push(AccountInfo::new(key, meta.is_signer, meta.is_writable, lamports, data, owner, acct.executable, 0));
        }
        let infos: &'static [AccountInfo<'static>] = Box::leak(infos.into_boxed_slice());
        let result = pdx_dark_protocol::entry(&ID, infos, &ix.data);
        if result.is_ok() {
            for info in infos.iter() {
                if info.is_writable {
                    let entry = self.accounts.get_mut(info.key).unwrap();
                    entry.data = info.try_borrow_data().unwrap().to_vec();
                    entry.lamports = info.lamports();
                }
            }
        }
        let logs = std::mem::take(&mut *LOGS.lock().unwrap());
        if record {
            self.history.push(PublicTx {
                accounts: ix.accounts.iter().map(|m| (m.pubkey, m.is_signer, m.is_writable)).collect(),
                data: ix.data.clone(),
                logs,
                success: result.is_ok(),
            });
        }
        result
    }

    fn token_amount(&self, key: &Pubkey) -> u64 {
        TokenAccountState::unpack(&self.accounts[key].data).unwrap().amount
    }
}

fn token_account(mint: Pubkey, owner: Pubkey, amount: u64) -> Vec<u8> {
    let mut data = vec![0u8; TokenAccountState::LEN];
    TokenAccountState {
        mint,
        owner,
        amount,
        delegate: COption::None,
        state: AccountState::Initialized,
        is_native: COption::None,
        delegated_amount: 0,
        close_authority: COption::None,
    }
    .pack_into_slice(&mut data);
    data
}

fn mint_account(supply: u64) -> Vec<u8> {
    let mut data = vec![0u8; MintState::LEN];
    MintState {
        mint_authority: COption::None,
        supply,
        decimals: 9,
        is_initialized: true,
        freeze_authority: COption::None,
    }
    .pack_into_slice(&mut data);
    data
}

fn vault_account() -> Vec<u8> {
    // Same bytes `initialize` produces: discriminator + zeroed state.
    let mut data = vec![0u8; 8 + std::mem::size_of::<Vault>()];
    data[..8].copy_from_slice(&Vault::DISCRIMINATOR);
    data
}

fn anchor_account<T: AccountSerialize>(value: &T, space: usize) -> Vec<u8> {
    let mut data = Vec::with_capacity(space);
    value.try_serialize(&mut data).unwrap();
    data.resize(space, 0);
    data
}

fn read_vault(data: &[u8]) -> Vault {
    bytemuck::pod_read_unaligned::<Vault>(&data[8..8 + std::mem::size_of::<Vault>()])
}

// ---------------------------------------------------------------------------
// Observer: public data only
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct DepositSeen {
    tx: usize,
    depositor: Pubkey,
    source_token_account: Pubkey,
    amount: u64,
    commitment: [u8; 32],
    leaf_index_log: Option<String>,
    whisper_logged: bool,
}

#[derive(Debug)]
struct WithdrawalSeen {
    tx: usize,
    amount: u64,
    commitment_public_input: [u8; 32],
    nullifier: [u8; 32],
    root: [u8; 32],
    mint: Pubkey,
    receiver_token: Pubkey,
    receiver: Pubkey,
    receiver_is_signer: bool,
}

struct LinkReport {
    deposits: Vec<DepositSeen>,
    withdrawal: WithdrawalSeen,
    candidates_by_amount: Vec<usize>,
    candidates_by_commitment: Vec<usize>,
}

/// Decodes successful program transactions with the public IDL layout and matches
/// the withdrawal against deposits. Inputs: public transaction records only.
fn observe(history: &[PublicTx]) -> LinkReport {
    let mut deposits = Vec::new();
    let mut withdrawal = None;
    for (tx, record) in history.iter().enumerate().filter(|(_, r)| r.success) {
        let (disc, body) = record.data.split_at(8);
        if disc == &ix_args::DepositWsolAndWhisper::DISCRIMINATOR[..] {
            let args = ix_args::DepositWsolAndWhisper::try_from_slice(body).unwrap();
            // IDL account order: vault, user, user_wsol, vault_wsol, token_program
            deposits.push(DepositSeen {
                tx,
                depositor: record.accounts[1].0,
                source_token_account: record.accounts[2].0,
                amount: args.amount,
                commitment: args.commitment,
                leaf_index_log: record.logs.iter().find(|l| l.starts_with("LEAF_INDEX:")).cloned(),
                whisper_logged: record.logs.iter().any(|l| l.starts_with("PDX_WHISPER:")),
            });
        } else if disc == &ix_args::PreparePhantomWithdrawV2::DISCRIMINATOR[..] {
            let args = ix_args::PreparePhantomWithdrawV2::try_from_slice(body).unwrap();
            // IDL account order: vault, mint, vault_token, receiver_token, receiver, token_program
            withdrawal = Some(WithdrawalSeen {
                tx,
                amount: args.amount,
                commitment_public_input: args.public_inputs[0],
                nullifier: args.nullifier_hash,
                root: args.root,
                mint: record.accounts[1].0,
                receiver_token: record.accounts[3].0,
                receiver: record.accounts[4].0,
                receiver_is_signer: record.accounts[4].1,
            });
        }
    }
    let withdrawal = withdrawal.expect("observer saw no successful withdrawal");
    let candidates_by_amount = deposits
        .iter()
        .enumerate()
        .filter(|(_, d)| d.amount == withdrawal.amount)
        .map(|(i, _)| i)
        .collect();
    let candidates_by_commitment = deposits
        .iter()
        .enumerate()
        .filter(|(_, d)| d.commitment == withdrawal.commitment_public_input)
        .map(|(i, _)| i)
        .collect();
    LinkReport { deposits, withdrawal, candidates_by_amount, candidates_by_commitment }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

// ---------------------------------------------------------------------------
// Scenario
// ---------------------------------------------------------------------------

#[test]
fn withdrawal_is_linkable_to_its_deposit_by_commitment() {
    program_stubs::set_syscall_stubs(Box::new(NativeStubs));
    let fx = load_fixture();
    assert_ne!(fx.commitments[0], fx.commitments[1], "fixture notes must be distinct");
    assert_eq!(fx.deposit_amount, fx.withdraw_amount);

    let token_program = spl_token::id();
    let (vault, _) = Pubkey::find_program_address(&[b"merkle_vault"], &ID);
    let (root_authority, _) = Pubkey::find_program_address(&[b"root_authority"], &ID);
    let nullifier_page_0 = pdx_dark_protocol::derive_nullifier_page_address(&vault, 0, &ID);
    let authority = Pubkey::new_unique();
    let depositors = [Pubkey::new_unique(), Pubkey::new_unique()];
    let depositor_tokens = [Pubkey::new_unique(), Pubkey::new_unique()];
    let vault_token = Pubkey::new_unique();

    let mut ledger = Ledger::default();
    ledger.put(token_program, anchor_lang::solana_program::bpf_loader::id(), vec![], true);
    ledger.put(fx.mint, token_program, mint_account(10_000_000), false);
    ledger.put(vault, ID, vault_account(), false);
    ledger.put(root_authority, ID, anchor_account(&RootAuthorityConfig { authority }, RootAuthorityConfig::SPACE), false);
    ledger.put(
        nullifier_page_0,
        ID,
        anchor_account(&NullifierPage { entries: [[0u8; 32]; pdx_dark_protocol::NULLIFIER_PAGE_CAP], count: 0 }, NullifierPage::SPACE),
        false,
    );
    ledger.put(authority, Pubkey::default(), vec![], false);
    ledger.put(fx.receiver, Pubkey::default(), vec![], false);
    ledger.put(vault_token, token_program, token_account(fx.mint, vault, 0), false);
    ledger.put(fx.receiver_token, token_program, token_account(fx.mint, fx.receiver, 0), false);
    for i in 0..2 {
        ledger.put(depositors[i], Pubkey::default(), vec![], false);
        ledger.put(depositor_tokens[i], token_program, token_account(fx.mint, depositors[i], 5_000_000), false);
    }

    // 1-2. Two deposits with distinct notes and identical amounts.
    for i in 0..2 {
        let ix = Instruction {
            program_id: ID,
            accounts: ix_accounts::DepositWsol {
                vault,
                user: depositors[i],
                user_wsol: depositor_tokens[i],
                vault_wsol: vault_token,
                token_program,
            }
            .to_account_metas(None),
            data: ix_args::DepositWsolAndWhisper {
                amount: fx.deposit_amount,
                commitment: fx.commitments[i],
                encrypted_note: vec![0xEE; 48],
                ephemeral_pubkey: [0x11 * (i as u8 + 1); 32],
                view_tag: 7 + i as u8,
            }
            .data(),
        };
        ledger.process(&ix, true).unwrap_or_else(|e| panic!("deposit {i} failed: {e:?}"));
    }
    assert_eq!(ledger.token_amount(&vault_token), 2 * fx.deposit_amount);

    // 3. Root authority posts the tree root containing both commitments.
    let ix = Instruction {
        program_id: ID,
        accounts: ix_accounts::UpdateRoot { vault, root_authority, authority }.to_account_metas(None),
        data: ix_args::UpdateRoot { new_root: fx.root }.data(),
    };
    ledger.process(&ix, true).expect("update_root");

    let withdraw_ix = |public_inputs: [[u8; 32]; 8], receiver_signs: bool| {
        let mut accounts = ix_accounts::PrepareWithdrawV2 {
            vault,
            mint: fx.mint,
            vault_token,
            receiver_token: fx.receiver_token,
            receiver: fx.receiver,
            token_program,
        }
        .to_account_metas(None);
        accounts[4].is_signer = receiver_signs;
        accounts.push(AccountMeta::new(nullifier_page_0, false));
        Instruction {
            program_id: ID,
            accounts,
            data: ix_args::PreparePhantomWithdrawV2 {
                amount: fx.withdraw_amount,
                nullifier_hash: fx.nullifier,
                root: fx.root,
                proof_a: fx.proof_a,
                proof_b: fx.proof_b,
                proof_c: fx.proof_c,
                public_inputs,
            }
            .data(),
        }
    };

    // Account constraint: the receiver wallet must sign the withdrawal.
    let unsigned = ledger.process(&withdraw_ix(fx.public_inputs, false), false);
    assert_eq!(unsigned, Err(ProgramError::Custom(ANCHOR_ACCOUNT_NOT_SIGNER)), "withdraw v2 must reject an unsigned receiver");

    // The commitment public input is bound by the proof: claiming note A's
    // commitment with note B's proof fails verification.
    let mut swapped = fx.public_inputs;
    swapped[0] = fx.commitments[0];
    assert_eq!(ledger.process(&withdraw_ix(swapped, true), false), Err(ProgramError::Custom(INVALID_PROOF)), "proof must bind public_inputs[0]");

    // 4. Valid withdrawal of note B through the real verifier.
    let vault_before = read_vault(&ledger.accounts[&vault].data);
    ledger.process(&withdraw_ix(fx.public_inputs, true), true).expect("valid withdrawal must succeed");
    let vault_after = read_vault(&ledger.accounts[&vault].data);
    assert_eq!(ledger.token_amount(&fx.receiver_token), fx.withdraw_amount);
    assert_eq!(ledger.token_amount(&vault_token), fx.deposit_amount);
    let withdraw_logs = &ledger.history.last().unwrap().logs;
    assert!(withdraw_logs.iter().any(|l| l.contains("ZK_VERIFY_V2")), "logs: {withdraw_logs:?}");

    // Replay of the same nullifier is rejected.
    assert_eq!(ledger.process(&withdraw_ix(fx.public_inputs, true), false), Err(ProgramError::Custom(DOUBLE_SPEND)), "nullifier replay must fail");

    // 5. Observer: public instruction data, account metas and logs only.
    let report = observe(&ledger.history);
    assert_eq!(report.deposits.len(), 2);
    assert_eq!(report.candidates_by_amount.len(), 2, "amount alone does not separate the deposits");
    assert_eq!(report.candidates_by_commitment, vec![1], "commitment equality identifies exactly one deposit");
    let linked = &report.deposits[report.candidates_by_commitment[0]];
    assert_eq!(linked.depositor, depositors[1]);
    assert_eq!(linked.source_token_account, depositor_tokens[1]);
    assert_eq!(linked.leaf_index_log.as_deref(), Some("LEAF_INDEX:1"));
    assert!(report.deposits.iter().all(|d| d.whisper_logged));

    let w = &report.withdrawal;
    assert_eq!(w.commitment_public_input, fx.commitments[1]);
    assert_eq!(w.amount, fx.withdraw_amount);
    assert_eq!(w.receiver_token, fx.receiver_token);
    assert_eq!(w.receiver, fx.receiver);
    assert!(w.receiver_is_signer);
    assert_eq!(w.mint, fx.mint);
    assert_eq!(w.nullifier, fx.nullifier);
    assert_eq!(w.root, fx.root);

    // Second, independent public path: the vault account state. Leaf commitments
    // and per-leaf deposited amounts are stored in plain account data, and the
    // withdrawal debits exactly the spent leaf.
    let leaf = |v: &Vault, i: usize| -> [u8; 32] { v.leaves[i * 32..(i + 1) * 32].try_into().unwrap() };
    assert_eq!(leaf(&vault_after, 0), fx.commitments[0]);
    assert_eq!(leaf(&vault_after, 1), fx.commitments[1]);
    let debited: Vec<usize> = (0..vault_after.next_index as usize)
        .filter(|&i| vault_before.deposited_amounts[i] != vault_after.deposited_amounts[i])
        .collect();
    assert_eq!(debited, vec![1], "vault state diff identifies the spent leaf");
    assert_eq!(vault_after.deposited_amounts[1], 0);
    assert_eq!(vault_after.deposited_amounts[0], fx.deposit_amount);

    println!("privacy linkage reproduction (public data only)");
    println!("  deposits observed: {}, candidates by amount: {}, candidates by commitment: {}",
        report.deposits.len(), report.candidates_by_amount.len(), report.candidates_by_commitment.len());
    println!("  linked deposit tx {} (depositor {}) -> withdrawal tx {} (receiver {}, receiver token {})",
        linked.tx, linked.depositor, w.tx, w.receiver, w.receiver_token);
    println!("  linking field: withdraw public_inputs[0] == deposit arg `commitment` = {}", hex(&w.commitment_public_input));
    println!("  also public: amount {}, mint {}, nullifier {}, root {}", w.amount, w.mint, hex(&w.nullifier), hex(&w.root));
    println!("  vault state: leaf commitments + deposited_amounts; debited leaf {:?}", debited);
}
