// Generate programs/dark-null-pool-v2/src/vk.rs from the transact_v2 snarkjs verification key (node >= 22, no deps).
// Usage: node gen_vk_rs.mjs <vk.json> <out vk.rs> [vk.json path as recorded in the header]
//
// Encoding (alt_bn128 syscall / EIP-197 format, as groth16-solana 0.2 expects; V2_SPEC 2.6):
//   G1 = x || y (32-byte big-endian each); G2 = x.c1 || x.c0 || y.c1 || y.c0.
// VK_BYTES = alpha_g1 || beta_g2 || gamma_g2 || delta_g2 || IC[0] || IC[1]  (576 bytes)
// VK_HASH  = SHA256(VK_BYTES): the `vk_hash` of PoolConfig and GET /v1/health (V2_SPEC 8.1, 8.8).
import fs from "node:fs";
import crypto from "node:crypto";

const [vkPath, outPath, label = "circuits/v2/build/vk.json"] = process.argv.slice(2);
const raw = fs.readFileSync(vkPath);
const vk = JSON.parse(raw.toString("utf8"));
const Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583n;

if (vk.protocol !== "groth16" || vk.curve !== "bn128") throw new Error("expected a groth16 bn128 key");
if (vk.nPublic !== 1 || vk.IC.length !== 2) throw new Error(`transact_v2 has exactly one public input; got nPublic=${vk.nPublic}`);

const be = (x) => {
  const v = BigInt(x);
  if (v < 0n || v >= Q) throw new Error("coordinate out of range");
  return Buffer.from(v.toString(16).padStart(64, "0"), "hex");
};
const g1 = (p) => {
  if (BigInt(p[2]) !== 1n) throw new Error("G1 point not affine");
  return Buffer.concat([be(p[0]), be(p[1])]);
};
const g2 = (p) => {
  if (BigInt(p[2][0]) !== 1n || BigInt(p[2][1]) !== 0n) throw new Error("G2 point not affine");
  return Buffer.concat([be(p[0][1]), be(p[0][0]), be(p[1][1]), be(p[1][0])]);
};

const alpha = g1(vk.vk_alpha_1);
const beta = g2(vk.vk_beta_2);
const gamma = g2(vk.vk_gamma_2);
const delta = g2(vk.vk_delta_2);
const ic = vk.IC.map(g1);
const vkBytes = Buffer.concat([alpha, beta, gamma, delta, ...ic]);
if (vkBytes.length !== 576) throw new Error("vk bytes length");
const vkHash = crypto.createHash("sha256").update(vkBytes).digest();
const jsonSha = crypto.createHash("sha256").update(raw).digest("hex");

const arr = (b, indent = "    ") => {
  const parts = [...b].map((x) => "0x" + x.toString(16).padStart(2, "0"));
  const lines = [];
  for (let i = 0; i < parts.length; i += 16) lines.push(indent + parts.slice(i, i + 16).join(", ") + ",");
  return "[\n" + lines.join("\n") + "\n" + indent.slice(4) + "]";
};

let out = "";
out += "//! transact_v2 Groth16 verifying key (BN254), `dev-setup`: single-operator phase 2 on PPoT `ppot_0080_16`.\n";
out += "//! The operator of a dev-setup phase 2 can forge proofs: devnet only (V2_SPEC 7.6, DESIGN 8.1).\n";
out += "//!\n";
out += "//! Generated by scripts/setup/gen_vk_rs.mjs; do not edit. Re-derive with scripts/setup/run_sandbox.sh rederive (B5).\n";
out += `//! Source: ${label}, SHA-256 ${jsonSha}.\n`;
out += "//! Encoding: G1 = x || y, G2 = x.c1 || x.c0 || y.c1 || y.c0, 32-byte big-endian (alt_bn128 syscalls).\n";
out += "//! One public input: `pi` (V2_SPEC 7.1). Proof A is negated by the client (V2_SPEC 2.6).\n";
out += "#![allow(dead_code)]\n\n";
out += "use groth16_solana::groth16::Groth16Verifyingkey;\n\n";
out += "/// Number of public inputs (`pi`).\n";
out += "pub const NR_PUBLIC_INPUTS: usize = 1;\n\n";
out += `/// SHA-256 of the source vk.json bytes.\npub const VK_JSON_SHA256: [u8; 32] = ${arr(Buffer.from(jsonSha, "hex"))};\n\n`;
out += `pub const VK_ALPHA_G1: [u8; 64] = ${arr(alpha)};\n\n`;
out += `pub const VK_BETA_G2: [u8; 128] = ${arr(beta)};\n\n`;
out += `pub const VK_GAMMA_G2: [u8; 128] = ${arr(gamma)};\n\n`;
out += `pub const VK_DELTA_G2: [u8; 128] = ${arr(delta)};\n\n`;
out += `pub const VK_IC: [[u8; 64]; 2] = [\n    ${arr(ic[0], "        ")},\n    ${arr(ic[1], "        ")},\n];\n\n`;
out += "/// alpha_g1 || beta_g2 || gamma_g2 || delta_g2 || IC[0] || IC[1].\n";
out += `pub const VK_BYTES: [u8; 576] = ${arr(vkBytes)};\n\n`;
out += "/// SHA-256(VK_BYTES): `vk_hash` in PoolConfig and in GET /v1/health.\n";
out += `pub const VK_HASH: [u8; 32] = ${arr(vkHash)};\n\n`;
out += "pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {\n";
out += "    nr_pubinputs: NR_PUBLIC_INPUTS,\n";
out += "    vk_alpha_g1: VK_ALPHA_G1,\n";
out += "    vk_beta_g2: VK_BETA_G2,\n";
out += "    vk_gamme_g2: VK_GAMMA_G2,\n";
out += "    vk_delta_g2: VK_DELTA_G2,\n";
out += "    vk_ic: &VK_IC,\n";
out += "};\n";

fs.writeFileSync(outPath, out);
console.log(JSON.stringify({ out: outPath, vk_json_sha256: jsonSha, vk_hash: vkHash.toString("hex"), bytes: out.length }));
