#!/bin/bash
# Host driver for the transact_v2 pipeline. Everything runs in throwaway containers; nothing is installed or
# built on the host, and no host directory is mounted (files are streamed in and out with tar).
#
#   run_sandbox.sh rederive   B5: re-derive the dev-setup verifying key from public inputs and compare with
#                             MANIFEST.json (circom release + PPoT file fetched and hash-checked, circuit
#                             recompiled, `snarkjs zkey verify`, vk.json and vk.rs regenerated byte for byte)
#   run_sandbox.sh test       witness tests (V-E2E pi, W1-W17) and a snarkjs proof per V-E2E step, against the
#                             committed build artifacts
#   run_sandbox.sh native     native witness path: build the circom C++ witness generator, check that it equals the
#                             WASM witness on every V-E2E step and refuses W1-W17 (B1 timing needs the Rust prover
#                             tool too; see docs/PHASE1_RESULTS.md)
#   run_sandbox.sh setup      new dev-setup key (overwrites circuits/v2/build/{transact_v2_dev.zkey,vk.json} and
#                             programs/dark-null-pool-v2/src/vk.rs, then MANIFEST.json rows)
#
# Requirements on the host: docker pointed at the sandbox VM (set DOCKER_CONTEXT), tar. Network is used only by the
# fetch step (npm ci --ignore-scripts, circom release binary, PPoT file); it is disconnected before any build or test.
# Results land in $OUT (default: a new mktemp directory); the script prints its path.
set -euo pipefail
export COPYFILE_DISABLE=1
CMD=${1:-}
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
OUT=${OUT:-$(mktemp -d)}
TAG=dn-circ-$$
NODE_IMG=node:22-bookworm-slim
AMD64_IMG=ubuntu:24.04
CIRCOM_URL=https://github.com/iden3/circom/releases/download/v2.2.3/circom-linux-amd64
CIRCOM_SHA=85342c7ff332d948df7c0c50ecf201e6129349aef550ce873f3c811b79fe53a3
PTAU_URL=https://pse-trusted-setup-ppot.s3.eu-central-1.amazonaws.com/pot28_0080/ppot_0080_16.ptau
PTAU_SHA=ed3622a7c79b0b49aadd134ebbc5b77df8c8c59bccebdfd0d9bf2c1a51561cf9

cleanup() { docker rm -f "$TAG-node" "$TAG-c" "$TAG-cpp" >/dev/null 2>&1 || true; }
trap cleanup EXIT

stage_repo() { # stream the files the pipeline reads into the node container at /w
  tar -C "$ROOT" -cf - \
    circuits/v2/transact_v2.circom circuits/v2/package.json circuits/v2/package-lock.json circuits/v2/test \
    circuits/v2/bench circuits/v2/build scripts/setup programs/dark-null-pool-v2/src/vk.rs MANIFEST.json \
    spikes/p0/circuits/transact_v2_spec.circom vectors/v2/V-E2E.json vectors/v2/V-ADDR.json \
    | docker exec -i "$TAG-node" tar -xf - -C /w
}

start_node() { # network on for the fetch step only
  docker run -d --name "$TAG-node" --memory 4g --tmpfs /w:rw,exec,size=2500m --tmpfs /tmp:rw,exec,size=512m -w /w "$NODE_IMG" sleep infinity >/dev/null
  stage_repo
  docker exec -w /w/circuits/v2 "$TAG-node" npm ci --ignore-scripts --no-audit --no-fund >/dev/null
  docker exec -w /w "$TAG-node" sh -c "mkdir -p bin ptau && node scripts/setup/fetch_pinned.mjs $CIRCOM_URL bin/circom $CIRCOM_SHA && chmod +x bin/circom"
  if [ "${NEED_PTAU:-0}" = 1 ]; then
    docker exec -w /w "$TAG-node" node scripts/setup/fetch_pinned.mjs "$PTAU_URL" ptau/ppot_0080_16.ptau "$PTAU_SHA" | tee "$OUT/ptau_fetch.json"
  fi
  docker network disconnect bridge "$TAG-node"
}

compile() { # official circom (x86_64 glibc) in an amd64 container without network; outputs to /w/rebuild (and /w/ref)
  docker run -d --name "$TAG-c" --platform linux/amd64 --network none --memory 3g --tmpfs /w:rw,exec,size=1500m -w /w "$AMD64_IMG" sleep infinity >/dev/null
  docker exec "$TAG-node" tar -C /w -cf - bin/circom circuits/v2/transact_v2.circom spikes/p0/circuits/transact_v2_spec.circom \
      circuits/v2/node_modules/circomlib/circuits scripts/setup/build_circuit.sh \
    | docker exec -i "$TAG-c" tar -xf - -C /w
  docker exec -w /w "$TAG-c" sh -c 'mkdir -p nm && ln -sfn /w/circuits/v2/node_modules/circomlib nm/circomlib && sh scripts/setup/build_circuit.sh /w bin/circom /w/nm /w/rebuild >/w/compile.log 2>&1; grep -a "non-linear constraints" /w/compile.log'
  local files="rebuild/transact_v2.r1cs rebuild/transact_v2_js/transact_v2.wasm rebuild/transact_v2_cpp compile.log"
  if [ "${WITH_REF:-0}" = 1 ]; then
    docker exec -w /w "$TAG-c" sh -c 'mkdir -p ref && bin/circom spikes/p0/circuits/transact_v2_spec.circom --O2 --r1cs --wasm -l /w/nm -o ref >/dev/null'
    files="$files ref/transact_v2_spec.r1cs ref/transact_v2_spec_js/transact_v2_spec.wasm"
  fi
  docker exec "$TAG-c" tar -C /w -cf - $files | docker exec -i "$TAG-node" tar -xf - -C /w
  docker rm -f "$TAG-c" >/dev/null
}

case "$CMD" in
  rederive)
    NEED_PTAU=1 start_node
    compile
    docker exec -w /w "$TAG-node" sh scripts/setup/rederive_dev_key.sh /w /w/rebuild /w/ptau/ppot_0080_16.ptau | tee "$OUT/b5_rederive.json"
    ;;
  test)
    start_node
    WITH_REF=1 compile
    docker exec -w /w/circuits/v2 "$TAG-node" sh -c 'mkdir -p /w/out \
      && node test/check_witness.mjs build/transact_v2.wasm build/transact_v2.r1cs /w/ref/transact_v2_spec_js/transact_v2_spec.wasm /w/ref/transact_v2_spec.r1cs /w/vectors/v2/V-E2E.json /w/vectors/v2/V-ADDR.json /w/out/witness_check_transact_v2.json 2>/dev/null \
      && node test/prove_verify.mjs build/transact_v2.wasm build/transact_v2_dev.zkey build/vk.json /w/vectors/v2/V-E2E.json /w/out/proofs_snarkjs.json \
      && node test/constraint_count.mjs build/transact_v2.r1cs /w/out/constraint_count.json'
    docker exec "$TAG-node" tar -C /w/out -cf - . | tar -xf - -C "$OUT"
    ;;
  native)
    start_node
    compile
    docker exec -w /w/circuits/v2 "$TAG-node" node test/write_inputs.mjs /w/vectors/v2/V-E2E.json /w/vectors/v2/V-ADDR.json /w/inputs
    docker run -d --name "$TAG-cpp" --memory 3g --tmpfs /w:rw,exec,size=1200m --tmpfs /var/lib/apt/lists:rw,size=200m \
      --tmpfs /var/cache/apt:rw,size=300m -w /w "$NODE_IMG" sleep infinity >/dev/null
    docker exec "$TAG-cpp" sh -c 'apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends g++ make libgmp-dev nlohmann-json3-dev >/dev/null'
    docker network disconnect bridge "$TAG-cpp"
    docker exec "$TAG-node" tar -C /w -cf - rebuild/transact_v2_cpp inputs scripts/setup/build_native_witness.sh circuits/v2/test/native_witness.sh \
      | docker exec -i "$TAG-cpp" tar -xf - -C /w
    docker exec "$TAG-cpp" sh /w/scripts/setup/build_native_witness.sh /w/rebuild/transact_v2_cpp
    docker exec "$TAG-cpp" bash /w/circuits/v2/test/native_witness.sh /w/rebuild/transact_v2_cpp /w/inputs /w/nout 15 2>/dev/null | tee "$OUT/native_witness_runs.jsonl" | grep tampered
    docker exec "$TAG-cpp" tar -C /w -cf - nout | docker exec -i "$TAG-node" tar -xf - -C /w
    docker exec -w /w/circuits/v2 "$TAG-node" node test/compare_wtns.mjs build/transact_v2.wasm build/transact_v2.r1cs /w/nout /w/vectors/v2/V-E2E.json /w/native_witness_check.json
    docker exec "$TAG-node" cat /w/native_witness_check.json > "$OUT/native_witness_check.json"
    ;;
  setup)
    NEED_PTAU=1 start_node
    docker exec -w /w "$TAG-node" sh scripts/setup/setup_dev_key.sh /w /w/circuits/v2/build /w/ptau/ppot_0080_16.ptau
    docker exec -w /w "$TAG-node" node scripts/setup/manifest_v2.mjs write /w /w/ptau/ppot_0080_16.ptau "$PTAU_URL" >/dev/null
    docker exec "$TAG-node" tar -C /w -cf - circuits/v2/build/transact_v2_dev.zkey circuits/v2/build/vk.json programs/dark-null-pool-v2/src/vk.rs MANIFEST.json \
      | tar -xf - -C "$ROOT"
    ;;
  *)
    echo "usage: $0 rederive|test|native|setup" >&2; exit 2;;
esac
echo "results: $OUT" >&2
