/**
 * Dark Null Protocol v1.22 — Public Type Definitions
 * 
 * These types represent the public interface for Dark Null Protocol.
 * Implementation details and prover types are intentionally not included.
 */

// Basic types
export type Bytes32 = number[];
export type PubkeyString = string;

// PendingCommit status enum
export enum CommitStatus {
  Pending = 0,
  Confirmed = 1,
  Rejected = 2,
  Finalized = 3,
}

/**
 * Public view of a PendingCommit account
 */
export interface PendingCommitPublic {
  /** 32B claim hash */
  commitment_hash: Bytes32;
  
  /** Unique spend identifier */
  nullifier_hash: Bytes32;
  
  /** Privacy-preserving recipient binding */
  blinded_recipient: Bytes32;
  
  /** Data availability reference (CID/hash) */
  proof_reference: Bytes32;
  
  /** Merkle root at commit time */
  root_hash: Bytes32;
  
  /** Withdrawal amount in lamports (as string for BigInt safety) */
  amount: string;
  
  /** Commit bond amount in lamports */
  bond_lamports: string;
  
  /** Slot when commit was created */
  commit_slot: string;
  
  /** Challenge window end slot */
  deadline_slot: string;
  
  /** Current status */
  status: CommitStatus;
  
  /** Original commit signer */
  submitter: PubkeyString;
  
  /** Expected destination */
  recipient_pubkey: PubkeyString;
  
  /** Expected relayer */
  relayer_pubkey: PubkeyString;
}

/**
 * Shield (deposit) parameters
 */
export interface ShieldParams {
  /** Amount to shield in lamports */
  amount: string;
  
  /** Commitment to add to anonymity set (generated by client) */
  commitment: Bytes32;
}

/**
 * CommitUnshieldV20 parameters (public interface)
 */
export interface CommitUnshieldParams {
  /** 32B claim hash */
  commitment_hash: Bytes32;
  
  /** Nullifier hash */
  nullifier_hash: Bytes32;
  
  /** Blinded recipient */
  blinded_recipient: Bytes32;
  
  /** Proof data availability reference */
  proof_reference: Bytes32;
  
  /** Root hash */
  root_hash: Bytes32;
  
  /** Amount in lamports */
  amount: string;
  
  /** Recipient public key */
  recipient: PubkeyString;
  
  /** Relayer public key (optional) */
  relayer?: PubkeyString;
}

/**
 * Receipt returned after successful operations
 */
export interface DarkNullReceipt {
  /** Commitment hash */
  commitment: string;
  
  /** Nullifier hash */
  nullifierHash: string;
  
  /** Protocol version */
  version: string;
  
  /** Transaction signature (if applicable) */
  txSignature?: string;
  
  /** Status */
  status: 'pending' | 'confirmed' | 'complete' | 'failed';
}

/**
 * Fee breakdown for a transfer
 */
export interface FeeBreakdown {
  /** Protocol fee in lamports */
  protocolFee: string;
  
  /** Relayer fee in lamports */
  relayerFee: string;
  
  /** Total fees */
  totalFees: string;
  
  /** Amount recipient receives */
  recipientReceives: string;
}
