//! BN254 scalar-field (Fr) byte encodings (V2_SPEC section 2).
//!
//! Every field element that crosses a boundary (instruction data, Poseidon syscall input, vectors,
//! circuit inputs) is a canonical 32-byte big-endian integer `< r`. Values `>= r` are rejected,
//! never reduced. Integers (amounts, epochs, indices) become field elements by value.

/// A field element (or any 32-byte big-endian integer) as bytes.
pub type Fr32 = [u8; 32];

/// The zero element.
pub const ZERO: Fr32 = [0u8; 32];

/// r = 21888242871839275222246405745257275088548364400416034343698204186575808495617 (BN254 Fr).
pub const R_BE: Fr32 = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93, 0xf0, 0x00, 0x00, 0x01,
];

/// l = order of the BabyJubJub prime-order subgroup generated by B8.
pub const L_BJJ_BE: Fr32 = [
    0x06, 0x0c, 0x89, 0xce, 0x5c, 0x26, 0x34, 0x05, 0x37, 0x0a, 0x08, 0xb6, 0xd0, 0x30, 0x2b, 0x0b,
    0xab, 0x3e, 0xed, 0xb8, 0x39, 0x20, 0xee, 0x0a, 0x67, 0x72, 0x97, 0xdc, 0x39, 0x21, 0x26, 0xf1,
];

/// `a < b` for 32-byte big-endian integers.
pub fn lt(a: &Fr32, b: &Fr32) -> bool {
    for i in 0..32 {
        if a[i] != b[i] {
            return a[i] < b[i];
        }
    }
    false
}

/// Canonical field element: `x < r`.
pub fn is_canonical(x: &Fr32) -> bool {
    lt(x, &R_BE)
}

/// Integer to field element (big-endian, by value).
pub const fn from_u64(v: u64) -> Fr32 {
    let b = v.to_be_bytes();
    let mut o = [0u8; 32];
    let mut i = 0;
    while i < 8 {
        o[24 + i] = b[i];
        i += 1;
    }
    o
}

/// `a - b` for 32-byte big-endian integers; requires `a >= b`.
pub fn sub(a: &Fr32, b: &Fr32) -> Fr32 {
    let mut o = [0u8; 32];
    let mut borrow = 0i16;
    for i in (0..32).rev() {
        let mut d = a[i] as i16 - b[i] as i16 - borrow;
        if d < 0 {
            d += 256;
            borrow = 1;
        } else {
            borrow = 0;
        }
        o[i] = d as u8;
    }
    o
}

/// `(a + b) mod r` for canonical inputs.
pub fn add_mod_r(a: &Fr32, b: &Fr32) -> Fr32 {
    let mut o = [0u8; 32];
    let mut carry = 0u16;
    for i in (0..32).rev() {
        let s = a[i] as u16 + b[i] as u16 + carry;
        o[i] = s as u8;
        carry = s >> 8;
    }
    if carry != 0 || !lt(&o, &R_BE) {
        // the true sum is below 2r, so one subtraction suffices; the 2^256 carry cancels in the wrap
        let mut d = [0u8; 32];
        let mut borrow = 0i16;
        for i in (0..32).rev() {
            let mut x = o[i] as i16 - R_BE[i] as i16 - borrow;
            if x < 0 {
                x += 256;
                borrow = 1;
            } else {
                borrow = 0;
            }
            d[i] = x as u8;
        }
        return d;
    }
    o
}

/// `r - v` (the field encoding of `-v`), and 0 for `v = 0`.
pub fn neg_u64(v: u64) -> Fr32 {
    if v == 0 {
        ZERO
    } else {
        sub(&R_BE, &from_u64(v))
    }
}

fn limbs(x: &Fr32) -> [u64; 4] {
    let mut l = [0u64; 4];
    for (i, limb) in l.iter_mut().enumerate() {
        let mut w = [0u8; 8];
        w.copy_from_slice(&x[32 - 8 * (i + 1)..32 - 8 * i]);
        *limb = u64::from_be_bytes(w);
    }
    l
}

/// `OS2IP(input) mod m` for a big-endian byte string of any length (used for 64-byte HKDF and
/// SHA-512 outputs). Bitwise long division; constant work per input bit, no allocation.
pub fn reduce_be(input: &[u8], modulus: &Fr32) -> Fr32 {
    let m = limbs(modulus);
    let mut rem = [0u64; 5];
    for byte in input {
        for bit in (0..8).rev() {
            let mut carry = ((byte >> bit) & 1) as u64;
            for limb in rem.iter_mut() {
                let next = *limb >> 63;
                *limb = (*limb << 1) | carry;
                carry = next;
            }
            // rem >= m ?
            let mut ge = rem[4] != 0;
            if !ge {
                ge = true;
                for i in (0..4).rev() {
                    if rem[i] != m[i] {
                        ge = rem[i] > m[i];
                        break;
                    }
                }
            }
            if ge {
                let mut borrow = 0u64;
                for i in 0..5 {
                    let mi = if i < 4 { m[i] } else { 0 };
                    let (d1, b1) = rem[i].overflowing_sub(mi);
                    let (d2, b2) = d1.overflowing_sub(borrow);
                    rem[i] = d2;
                    borrow = (b1 | b2) as u64;
                }
            }
        }
    }
    let mut o = [0u8; 32];
    for i in 0..4 {
        o[32 - 8 * (i + 1)..32 - 8 * i].copy_from_slice(&rem[i].to_be_bytes());
    }
    o
}

/// 32 hash bytes to a field element: the first 31 bytes, big-endian (248 bits, always `< r`).
pub fn h248(b: &[u8; 32]) -> Fr32 {
    let mut o = [0u8; 32];
    o[1..].copy_from_slice(&b[..31]);
    o
}

/// A 32-byte public key (mint, program id) as two field elements: `(BE(pk[0..16]), BE(pk[16..32]))`.
pub fn pubkey_fields(pk: &[u8; 32]) -> (Fr32, Fr32) {
    let mut hi = [0u8; 32];
    let mut lo = [0u8; 32];
    hi[16..].copy_from_slice(&pk[..16]);
    lo[16..].copy_from_slice(&pk[16..]);
    (hi, lo)
}

/// Little-endian 32-byte form of a big-endian integer (BabyJubJub `S`, ed25519 scalars).
pub fn reverse(x: &Fr32) -> Fr32 {
    let mut o = *x;
    o.reverse();
    o
}
